---
#-
#                      _
#  _ __ ___  _   _ ___(_) ___
# | '_ ` _ \| | | / __| |/ __|
# | | | | | | |_| \__ \ | (__
# |_| |_| |_|\__,_|___/_|\___|
#
#
#- from github.com/basnijholt/home-assistant-config
- alias: "Music: start playlist"
  initial_state: "on"
  triggers:
    trigger: state
    entity_id: input_boolean.start_the_music
    from: "off"
    to: "on"
  actions:
    - action: input_boolean.turn_off
      entity_id: input_boolean.start_the_music
    - action: script.start_spotify_playlist_of_nearest_person
      data:
        source: KEF LS50
        entity_id: media_player.kef_ls50

- alias: "Music: switch music from iPhone to speakers if coming home"
  triggers:
    trigger: state
    entity_id: binary_sensor.openclose_front_door
    from: "off"
    to: "on"
  conditions:
    - condition: state
      entity_id: person.marcella
      state: not_home
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - "{{ is_state_attr('media_player.spotify', 'source', 'basnijholt-iphone') }}"
    - "{{ is_state('media_player.spotify', 'playing') }}"
    - "{{ as_timestamp(now()) - as_timestamp(states.person.bas.last_changed) < 5 * 60 }}" # recently got home
    - condition: numeric_state
      entity_id: proximity.home
      below: 2
  actions:
    - action: media_player.turn_on
      entity_id: media_player.kef_ls50
    - action: media_player.select_source
      entity_id: media_player.kef_ls50
      data:
        source: Wifi
    - action: media_player.select_source
      entity_id: media_player.spotify
      data:
        source: KEF LS50
