---
#-
#        _   _ _ _ _   _
#  _   _| |_(_) (_) |_(_) ___  ___
# | | | | __| | | | __| |/ _ \/ __|
# | |_| | |_| | | | |_| |  __/\__ \
#  \__,_|\__|_|_|_|\__|_|\___||___/
#
#
#- from github.com/basnijholt/home-assistant-config

- alias: "Utilities: washing machine or dishwasher started or finished"
  triggers:
    - platform: state
      entity_id: binary_sensor.dishwasher
    - platform: state
      entity_id: binary_sensor.washing_machine
  variables:
    from_state: "{{ trigger.from_state.state }}"
    to_state: "{{ trigger.to_state.state }}"
    name: "{{ trigger.entity_id.split('.', 1)[1] }}"
  conditions: "{{ (to_state == 'on' and from_state == 'off') or (to_state == 'off' and from_state == 'on') }}"
  actions:
    service: input_datetime.set_datetime
    data:
      entity_id: "input_datetime.{{ name }}_{{ to_state }}"
      timestamp: "{{ now().timestamp() }}"

- alias: "Utilities: washing machine notification"
  triggers:
    platform: state
    entity_id: binary_sensor.washing_machine
    from: "off"
    to: "on"
  actions:
    service: script.utility_notification
    data:
      name: "washing_machine"
      emojis: "👚👕"

- alias: "Utilities: dishwasher notification"
  triggers:
    platform: state
    entity_id: binary_sensor.dishwasher
    from: "off"
    to: "on"
  actions:
    service: script.utility_notification
    data:
      name: "dishwasher"
      emojis: "🍽🍳"
